In [ ]:
pandas.read_json(path_or_buf=None, orient=None, typ='frame', dtype=True, convert_axes=True, convert_dates=True, keep_default_dates=True, numpy=False, precise_float=False, date_unit=None, encoding=None, lines=False, chunksize=None, compression='infer')

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import json

In [93]:
os.chdir(r'F:\AppliedDataScience\data\millionsong\lastfm_similarity\lastfm_subset\A\A\A')

# Reading the json as a dict
with open('TRAAAAW128F429D538.json') as json_data:
    data = json.load(json_data)

# using the from_dict load function. Note that the 'orient' parameter 
#is not using the default value (or it will give the same error that you got before)
# We transpose the resulting df and set index column as its index to get this result
#pd.DataFrame.from_dict(data, orient='index').T.set_index('index')

In [94]:
df = [data]

In [95]:
type(df)

list

In [96]:
df_1 = pd.DataFrame(df)

In [97]:
df_1

,artist,similars,tags,timestamp,title,track_id
0,Casual,"[[TRABACN128F425B784, 0.871737], [TRIAINV12903...","[[Bay Area, 100], [hieroglyiphics, 100], [clas...",2011-08-02 20:13:25.674526,I Didn't Mean To,TRAAAAW128F429D538

In [98]:
path_to_json = r'F:\AppliedDataScience\data\millionsong\lastfm_similarity\lastfm_subset\A\A\A'
json_files = [pos_json for pos_json in os.listdir(path_to_json) if pos_json.endswith('.json')]
json_files = pd.DataFrame(json_files)
json_files

                          0
0   TRAAAAW128F429D538.json
1   TRAAABD128F429CF47.json
2   TRAAADZ128F9348C2E.json
3   TRAAAEF128F4273421.json
4   TRAAAFD128F92F423A.json
5   TRAAAMO128F1481E7F.json
6   TRAAAMQ128F1460CD3.json
7   TRAAAPK128E0786D96.json
8   TRAAARJ128F9320760.json
9   TRAAAVG12903CFA543.json
10  TRAAAVO128F93133D4.json

In [99]:
json_files.iloc[1:2]

                         0
1  TRAAABD128F429CF47.json

In [116]:
os.chdir(r'F:\AppliedDataScience\data\millionsong\lastfm_similarity\lastfm_subset\A\A\A')

# Reading the json as a dict

with open('TRAAAAW128F429D538.json') as json_data:
        
    d1 = json.load(json_data)
with open('TRAAABD128F429CF47.json') as json_data:
        
    d2 = json.load(json_data)
with open('TRAAADZ128F9348C2E.json') as json_data:
        
    d3 = json.load(json_data)
with open('TRAAAEF128F4273421.json') as json_data:
        
    d4 = json.load(json_data)
with open('TRAAAFD128F92F423A.json') as json_data:
        
    d5 = json.load(json_data)
with open('TRAAAMO128F1481E7F.json') as json_data:
        
    d6 = json.load(json_data)
with open('TRAAAMQ128F1460CD3.json') as json_data:
        
    d7 = json.load(json_data)
with open('TRAAAPK128E0786D96.json') as json_data:
    
    d8 = json.load(json_data)
    
with open('TRAAARJ128F9320760.json') as json_data:
    
    d9 = json.load(json_data)
with open('TRAAAVG12903CFA543.json') as json_data:
    
    d10 = json.load(json_data)
with open('TRAAAVO128F93133D4.json') as json_data:
    
    d11 = json.load(json_data)

In [111]:
d1_sim = pd.DataFrame(d1['similars'])

In [115]:
d1_sim

                     0         1
0   TRABACN128F425B784  0.871737
1   TRIAINV12903CB4943  0.751301
2   TRJYGLF12903CB4952  0.751052
3   TRVNXHF128F93134F0  0.582662
4   TRWJMMB128F429D550  0.508661
5   TRUEULA128F425B7DB  0.404535
6   TRIEUIZ128F427973B  0.028357
7   TRWNLAW128F9364539  0.027889
8   TRWIMTU128F148D424  0.022798
9   TRPTKMG128F930E997  0.019806
10  TRQIPME12903CE0A48  0.016187
11  TRAOGGC128F4215EB5  0.015865
12  TROIDMT128F428ED1F  0.015864
13  TRAKXGR128F428686F  0.015672
14  TRQKESV128F428B3AC  0.015541
15  TRCRZMU128F931E6C0  0.015405
16  TRKDOBN12903D0C783  0.015242
17  TRXVODK12903D0C786  0.015242
18  TRIVHFX12903D0CCF0  0.014552
19  TRUZARV12903D0CCE5  0.014552
20  TRTSCMP12903CB5891  0.014353
21  TRWGIRJ128F425DCB2  0.014103
22  TRZEKXA128F9342FFC  0.013912
23  TRHVRPE128F934DB59  0.013449
24  TRZYTKI128F42B7B00  0.013368
25  TRJAUFI128F930D04B  0.013097
26  TRMXJBM128F145A603  0.012836
27  TRDBMBY128F934DB61  0.012740
28  TRAZHAJ128F4289AE1  0.012584
29  TRZEXUH128F934816E  0.012389
..                 ...       ...
43  TRRTKBE128F92E865C  0.010400
44  TROMXLL128F93221D8  0.010009
45  TRMYPAA128F428CDC2  0.009865
46  TRWXSCE128F92FC6AE  0.009833
47  TRTCRUU128F429F34C  0.009831
48  TRLYIBM128F933B0EA  0.009422
49  TRICXMC12903CC8A7A  0.009351
50  TRGHVHI12903CD6DFD  0.009217
51  TRVXNHI12903CBF3A1  0.009136
52  TRBOXGO128F93148B7  0.009036
53  TRHFVQE128F9348164  0.008977
54  TRLOFDB128F92EED97  0.008651
55  TRHIHNQ128F92F8954  0.008491
56  TRICCJR128F42630F2  0.008480
57  TRLTLII128F4262BB5  0.008480
58  TRSPPUZ128F92D42F5  0.008123
59  TRDIXKU128F4276706  0.008053
60  TRXUIOA128F426DE47  0.008053
61  TRZRBQH128F934DF59  0.008052
62  TRSRQXJ128F4236BA4  0.008052
63  TRMUYLY128F92E734D  0.008036
64  TRXTAPD128F145A606  0.008036
65  TRTTVGT128F9322194  0.007894
66  TRDGEKT128F93221D3  0.007894
67  TRGCTAI128F93223F1  0.007860
68  TRLYHQW12903CB4D32  0.007808
69  TRHSXDE128F1456DD5  0.007761
70  TRAMLHO128F93224CB  0.007716
71  TRMPZMN128F93224B3  0.007716
72  TRBAJMS128EF356971  0.007673

[73 rows x 2 columns]

In [114]:
d1_tag = pd.DataFrame(d1['tags'])
d1_tag

                                                   0    1
0                                           Bay Area  100
1                                     hieroglyiphics  100
2                                            classic   50
3                                            Hip-Hop   50
4                                             stream   50
5                                                 OG   50
6  1979-2006: A Hip-Hop Odyssey - 800 Tracks In A...   50
7                                      heiroglyphics   50
8                                        oaksterdamn   50
9                                   heard on Pandora    0

In [102]:
df_1

,artist,similars,tags,timestamp,title,track_id
0,Casual,"[[TRABACN128F425B784, 0.871737], [TRIAINV12903...","[[Bay Area, 100], [hieroglyiphics, 100], [clas...",2011-08-02 20:13:25.674526,I Didn't Mean To,TRAAAAW128F429D538

In [119]:
d2 = [d2]
df_2 = pd.DataFrame(d2)
d3 = [d3]
df_3 = pd.DataFrame(d3)
d4 = [d4]
df_4 = pd.DataFrame(d4)
d5 = [d5]
df_5 = pd.DataFrame(d5)
d6 = [d6]
df_6 = pd.DataFrame(d6)
d7 = [d7]
df_7 = pd.DataFrame(d7)
d8 = [d8]
df_8 = pd.DataFrame(d8)
d9 = [d9]
df_9 = pd.DataFrame(d9)
d10 = [d10]
df_10 = pd.DataFrame(d10)
d11 = [d11]
df_11 = pd.DataFrame(d11)

In [131]:
df_1

,artist,similars,tags,timestamp,title,track_id
0,Casual,"[[TRABACN128F425B784, 0.871737], [TRIAINV12903...","[[Bay Area, 100], [hieroglyiphics, 100], [clas...",2011-08-02 20:13:25.674526,I Didn't Mean To,TRAAAAW128F429D538

In [132]:
df_2

,artist,similars,tags,timestamp,title,track_id
0,The Box Tops,"[[TRBRSNN128F4284E8C, 1], [TRHYADV128F4285EC1,...","[[60s, 100], [soul, 52], [pop, 41], [rock, 35]...",2011-08-12 04:04:21.577908,Soul Deep,TRAAABD128F429CF47

In [135]:
similar_df_1 = pd.concat([df_1, df_2,df_3,df_4,df_5,df_6,df_7,df_8,df_9,df_10,df_11], axis=0)

In [136]:
similar_df_1

,artist,similars,tags,timestamp,title,track_id
0,Casual,"[[TRABACN128F425B784, 0.871737], [TRIAINV12903...","[[Bay Area, 100], [hieroglyiphics, 100], [clas...",2011-08-02 20:13:25.674526,I Didn't Mean To,TRAAAAW128F429D538
0,The Box Tops,"[[TRBRSNN128F4284E8C, 1], [TRHYADV128F4285EC1,...","[[60s, 100], [soul, 52], [pop, 41], [rock, 35]...",2011-08-12 04:04:21.577908,Soul Deep,TRAAABD128F429CF47
0,La Sonora Santanera,"[[TRPHLNJ128F9348769, 1], [TRVWNCB128F9343925,...","[[latin, 100]]",2011-08-09 18:24:38.890272,Amor De Cabaret,TRAAADZ128F9348C2E
0,Adam Ant,"[[TRWXGJB12903CCFE02, 1], [TRKDLTP128F427F677,...","[[new wave, 100], [80s, 66], [freedom, 33], [s...",2011-08-11 21:57:49.876264,Something Girls,TRAAAEF128F4273421
0,Gob,"[[TRTOVWD128F92F4227, 1], [TRUXNUD128F92F41D0,...","[[punk rock, 100], [punk, 60]]",2011-08-09 01:59:41.352247,Face the Ashes,TRAAAFD128F92F423A
0,Jeff And Sheri Easter,"[[TRSNSGQ128F42276FD, 0.845623], [TRSPQON12903...",[],2011-09-07 23:46:34.790080,The Moon And I (Ordinary Day Album Version),TRAAAMO128F1481E7F
0,Rated R,"[[TRXHNRQ128F1460CDB, 1], [TRIIZJX128F1460CE5,...",[],2011-08-11 21:18:23.312581,Keepin It Real (Skit),TRAAAMQ128F1460CD3
0,Tweeterfriendly Music,"[[TRSFTWF128F4243F7D, 0.012599], [TRRVVGE12903...",[],2011-08-03 00:30:31.051080,Drop of Rain,TRAAAPK128E0786D96
0,Planet P Project,"[[TRPUQJR128F9320769, 1], [TROGAAI128F932076D,...","[[Progressive rock, 100], [prog rock, 100], [b...",2011-08-09 16:39:17.211274,Pink World,TRAAARJ128F9320760
0,CLP,[],[],2011-08-02 06:36:59.879759,Insatiable (Instrumental Version),TRAAAVG12903CFA543
0,Jennyanykind,[],[],2011-08-12 10:41:03.336417,Young Boy Blues,TRAAAVO128F93133D4